### ISSUE TITLE
What is the correct format for the .json

### ISSUE THREAD

**Issue by ambitionist** [alyanser/dolladolla#2]
It seems like the .README.json is not there so I wanted to know what was format looking like

**Comment by alyanser** [comment]
@ambitionist I used "Export cookie JSON file for Puppeteer" Chrome extension to export the cookies.
Even if you got the cookies in Netscape format, you can us <a>https://www.cookieconverter.com</a> to convert them to JSON.

**Comment by ambitionist** [comment]
Thank you for the reply, really awesome project by the way!
