### ISSUE TITLE
assert cookie["sameSite"] in ["None", "Strict", "Lax"]

### ISSUE THREAD

**Issue by yasararafat009** [alyanser/dolladolla#5]
assert cookie["sameSite"] in ["None", "Strict", "Lax"] -- How to fix this 
After running the code i got this assertion error

PYthon 3.10

**Comment by alyanser** [comment]
What's the value of your "sameSite" cookie? Can you try just refreshing your cookies and trying again? Also providing a traceback will be helpful.

P.S. this project is no longer maintained so expect some delay.
